---
# Elasticsearch Ansible Tasks

# Install Java
- include: java.yml
  when: elasticsearch_install_java

# Configure timezome
- include: timezone.yml

# Install and configure elasticsearch
- include: elastic-install.yml